### ISSUE TITLE
It's a mess

### ISSUE THREAD

**Issue by MaxLi3** [banana-news/reports#4]
Albert, what happened?????
<img width="1440" alt="Screenshot 2024-05-17 at 19 53 37" src="https://github.com/banana-news/banana/assets/95269784/0f581982-6415-4c14-94ca-239ef707edd0">

<img width="1440" alt="Screenshot 2024-05-17 at 19 53 52" src="https://github.com/banana-news/banana/assets/95269784/9723b8fa-9382-42de-a94a-85cc198a61ba">

**Comment by albertkemp** [comment]
The div styling for width was set at 45% which made it overflow onto the next line. I have fixed that. Also, that page over there is like that because I moved all the translations into a translations folder which made the links to the stylesheets and images incorrect. I have fixed both issues.
