### ISSUE TITLE
Mobile screen topnav doesn't work on searchresults.html

### ISSUE THREAD

**Issue by albertkemp** [banana-news/reports#6]
When you test searchresults.html in mobile the bars button does not make the topnav come down.

**Comment by albertkemp** [comment]
Probably just 1 thing that people forgot to do or link to

**Comment by MaxLi3** [comment]
It works for my 15ProMax, It just makes the dropdown mushed with the searchbutton

**Comment by MaxLi3** [comment]
Now that's an issue on like every page

**Comment by MaxLi3** [comment]
It only mushes when you click the drop-down

**Comment by MaxLi3** [comment]
And you want to _close_ it

**Comment by MaxLi3** [comment]
Afterwards

**Comment by albertkemp** [comment]
no I think it works on other pages

**Comment by albertkemp** [comment]
Oh I tested it and now it works
